bme_gpu24
start on Sun Dec 17 19:23:46 CST 2023
/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/public/home/v-jianght/projects/cervical-cancer/train_distribute.py", line 17, in <module>
Traceback (most recent call last):
  File "/public/home/v-jianght/projects/cervical-cancer/train_distribute.py", line 17, in <module>
    from models.vit_res_model import VitRes,VitResMoE
  File "/public/home/v-jianght/projects/cervical-cancer/models/vit_res_model.py", line 4, in <module>
    from models.vit_res_model import VitRes,VitResMoE
  File "/public/home/v-jianght/projects/cervical-cancer/models/vit_res_model.py", line 4, in <module>
    from models.vit_moe import vit_multi_long_tail_MoE
  File "/public/home/v-jianght/projects/cervical-cancer/models/vit_moe.py", line 12, in <module>
    from models.vit_moe import vit_multi_long_tail_MoE
  File "/public/home/v-jianght/projects/cervical-cancer/models/vit_moe.py", line 12, in <module>
    from models.custom_moe_layer import FMoETransformerMLP
  File "/public/home/v-jianght/projects/cervical-cancer/models/custom_moe_layer.py", line 6, in <module>
    from models.custom_moe_layer import FMoETransformerMLP
  File "/public/home/v-jianght/projects/cervical-cancer/models/custom_moe_layer.py", line 6, in <module>
    from fmoe.layers import FMoE, _fmoe_general_global_forward
ModuleNotFoundError    : from fmoe.layers import FMoE, _fmoe_general_global_forwardNo module named 'fmoe'

ModuleNotFoundError: No module named 'fmoe'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30946) of binary: /public/home/v-jianght/anaconda3/envs/pytorch/bin/python
Traceback (most recent call last):
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/public/home/v-jianght/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_distribute.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-17_19:23:54
  host      : bme_gpu24
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 30947)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-17_19:23:54
  host      : bme_gpu24
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 30946)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
end on Sun Dec 17 19:23:55 CST 2023
